# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- deprecated/**/*
- "src/parsers/jpg.js"
- "src/parsers/jpx.js"
- "src/controls/Orbit2DControls_old.js"